run:
  concurrency: 4
  issues-exit-code: 1
linters-settings:
  tenv:
    # The option `all` will run against whole test files (`_test.go`) regardless of method/function signatures.
    # Otherwise, only methods that take `*testing.T`, `*testing.B`, and `testing.TB` as arguments are checked.
    # Default: false
    all: true
  gosimple:
    checks: ["-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1022"]
  misspell:
    locale: US
linters:
  disable-all: true
  fast: false
  enable:
    - asciicheck
    - gofmt
    - gosimple
