package main

import (
	"github.com/vertgenlab/gonomics/exception"
	"github.com/vertgenlab/gonomics/fileio"
	"math"
	"os"
	"testing"
)

var WigMathTests = []struct {
	InFile                 string
	OutFile                string
	ChromSizes             string
	BedMask                string
	MinValue               float64
	MaxValue               float64
	ExpectedFile           string
	ScalarMultiply         float64
	ScalarDivide           float64
	AddFile                string
	MaxFile                string
	SubtractFile           string
	MovingAverageSmoothing int
	AbsoluteError          string
	AbsolutePercentError   string
	Missing                float64
	MissingBed             bool
	Pearson                string
	SamplingFrequency      float64
}{
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.add.wig",
		ExpectedFile:           "testdata/math/expected.add.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "testdata/math/second.wig",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.wig",
		ExpectedFile:           "testdata/math/expected.subtract.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "testdata/math/second.wig",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/unsmooth.wig",
		ChromSizes:             "testdata/math/smooth.chrom.sizes",
		OutFile:                "testdata/math/tmp.smooth.wig",
		ExpectedFile:           "testdata/math/expected.smooth.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 5,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.absError.wig",
		ExpectedFile:           "testdata/math/expected.absError.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "testdata/math/second.wig",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.absPercentError.wig",
		ExpectedFile:           "testdata/math/expected.absPercentError.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "testdata/math/second.wig",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.Pearson.txt",
		ExpectedFile:           "testdata/math/expected.Pearson.txt",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "testdata/math/second.wig",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.Mult55.wig",
		ExpectedFile:           "testdata/math/expected.mult55.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         55,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.divide4.wig",
		ExpectedFile:           "testdata/math/expected.divide4.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           4,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.min25.wig",
		ExpectedFile:           "testdata/math/expected.min25.wig",
		BedMask:                "",
		MinValue:               25,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.wig",
		ChromSizes:             "testdata/math/genome.chrom.sizes",
		OutFile:                "testdata/math/tmp.max300.wig",
		ExpectedFile:           "testdata/math/expected.max300.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               300,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.missing.wig",
		ChromSizes:             "testdata/math/missing.chrom.sizes",
		OutFile:                "testdata/math/tmp.missing.bed",
		ExpectedFile:           "testdata/math/expected.missing.bed",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             true,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.missing.wig",
		ChromSizes:             "testdata/math/missing.chrom.sizes",
		OutFile:                "testdata/math/tmp.masked.wig",
		ExpectedFile:           "testdata/math/expected.masked.wig",
		BedMask:                "testdata/math/mask.bed",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
	{
		InFile:                 "testdata/math/in.max.wig",
		ChromSizes:             "testdata/math/max.chrom.sizes",
		OutFile:                "testdata/math/tmp.max.wig",
		ExpectedFile:           "testdata/math/expected.max.wig",
		BedMask:                "",
		MinValue:               -1 * math.MaxFloat64,
		MaxValue:               math.MaxFloat64,
		ScalarMultiply:         1,
		ScalarDivide:           1,
		AddFile:                "",
		MaxFile:                "testdata/math/second.wig",
		SubtractFile:           "",
		MovingAverageSmoothing: 1,
		AbsoluteError:          "",
		AbsolutePercentError:   "",
		Missing:                -10,
		MissingBed:             false,
		Pearson:                "",
		SamplingFrequency:      1,
	},
}

func TestWigMath(t *testing.T) {
	var err error
	var s MathSettings
	for _, v := range WigMathTests {
		s = MathSettings{
			InFile:                 v.InFile,
			ChromSizes:             v.ChromSizes,
			OutFile:                v.OutFile,
			BedMask:                v.BedMask,
			MinValue:               v.MinValue,
			MaxValue:               v.MaxValue,
			ScalarMultiply:         v.ScalarMultiply,
			ScalarDivide:           v.ScalarDivide,
			ElementWiseAdd:         v.AddFile,
			ElementWiseMax:         v.MaxFile,
			ElementWiseSubtract:    v.SubtractFile,
			MovingAverageSmoothing: v.MovingAverageSmoothing,
			AbsoluteError:          v.AbsoluteError,
			AbsolutePercentError:   v.AbsolutePercentError,
			Missing:                v.Missing,
			MissingBed:             v.MissingBed,
			Pearson:                v.Pearson,
			SamplingFrequency:      v.SamplingFrequency,
		}
		wigMath(s)
		if !fileio.AreEqual(v.OutFile, v.ExpectedFile) {
			t.Errorf("Error in wigMath. Output was not as expected.")
		} else {
			err = os.Remove(v.OutFile)
			exception.PanicOnErr(err)
		}
	}
}
