name: Go Pull Request Check
on:
  push:
    branches: main
  pull_request:
    branches: main
env:
  GOLANG: stable
jobs:
  build-and-test:
    name: Build and test gonomics repo on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG }}

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
