on:
  workflow_call:
    inputs:
      GOLANG:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GOLANG }}
      - name: Setup lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
      - name: Lint and automate clean
        run: golangci-lint run ./... --fix
